### PR TITLE
Switch from AddVectoredExceptionHandler to SetUnhandledExceptionFilter to avoid false positives

### LINKED ISSUE #2332: Catch2 fails tests when exception C00000005 is thrown then caught
**Describe the bug**
Catch2 marks tests as failed when a continuable C0000005 exception is raised and caught by a test. 

**Expected behavior**
Tests should be marked as failed only when non-continuable exceptions are raised or exceptions are not handled.

**Reproduction steps**
Steps to reproduce the bug.
```
#define CATCH_CONFIG_MAIN

#include <iostream>
#include <Windows.h>
#include "catch2\catch.hpp"

void throw_and_catch()
{
    __try {
        RaiseException(0xC0000005, 0, 0, NULL);
    }
    __except (1)
    {

    }
}


TEST_CASE("foo", "[bar]")
{
    throw_and_catch();
}
```

**Platform information:**

 - OS: Windows 11, build 22523.1002.amd64fre.rs_onecore_stack.211210-1950
 - Compiler+version: VS 2022 / CL version 19.30.30706.
 - Catch version: 2.8.0

**Additional context**
The Visual Studio AddressSanitizer relies on catching and handling 0xC0000005 structured exceptions as part of its logic. This behavior in Catch breaks ASAN.

### PR DESCRIPTION
**Pull request by Alan-Jowett**
### What
Catch2 incorrectly registers for SIGSEGV and other signals on Windows. The correct behavior is to register as the top-level unhandled exception filter so that it is notified last after the application has had an opportunity to handle the exception and after the debugger has been notified. The previous behavior was to register a vectored exception handler which results in Catch2 being notified prior to the application being able to handle the exception.

### Why
Visual Studio 2022 uses structured exceptions to implement address sanitization (/fsanitize=address). This issue results in Catch2 being incompatible with a key bug-finding feature of VS 2022. 

## GitHub Issues
Closes #2332 

## Notes for maintainers
I didn't see any Windows-specific tests and I am unsure how to validate the new behavior in the CI/CD pipeline. I manually verified the change fixes the issue but would prefer to add a new test to the CI/CD pipeline if possible.

Signed-off-by: Alan Jowett <alanjo@microsoft.com>

### CODE REVIEW

File: src/catch2/internal/catch_fatal_condition_handler.cpp [hunk 1]
```diff
@@ -120,18 +120,15 @@ namespace Catch {
...
-        }
+        // Register as a the top level exception filter.
+        previousTopLevelExceptionFilter = SetUnhandledExceptionFilter(topLevelExceptionFilter);
     }
 
     void FatalConditionHandler::disengage_platform() {
-        if (!RemoveVectoredExceptionHandler(exceptionHandlerHandle)) {
-            CATCH_RUNTIME_ERROR("Could not unregister vectored exception handler");
+        if (SetUnhandledExceptionFilter(reinterpret_cast<LPTOP_LEVEL_EXCEPTION_FILTER>(previousTopLevelExceptionFilter)) != topLevelExceptionFilter) {
+            CATCH_RUNTIME_ERROR("Could not restore previous top level exception filter");
```
Comment (horenmar) [inline src/catch2/internal/catch_fatal_condition_handler.cpp:129]: I am not sure that the correct response to our filter being overridden is to error out.

Comment (Alan-Jowett) [reply src/catch2/internal/catch_fatal_condition_handler.cpp:129]: This should only fire if the test fails to restore the unhandled exception filter state. Well-behaved libraries and code should return the process state prior to returning.

Comment (horenmar) [reply src/catch2/internal/catch_fatal_condition_handler.cpp:129]: Makes sense.

**Comment by horenmar** [comment]
Do I assume correctly that this will also fix #2286 and probably #898 as well?

**Comment by Alan-Jowett** [comment]
Added test to Misc.tests.cpp to validate modified SEH handling behavior on Windows. If this is the wrong test to add it to, let me know and I can move it.

**Comment by Alan-Jowett** [comment]
> Do I assume correctly that this will also fix #2286 and probably #898 as well?

It should based on the description in the issues.

File: tests/SelfTest/UsageTests/Misc.tests.cpp [hunk 2]
```diff
@@ -18,9 +18,6 @@
 #include <limits>
 #include <array>
 #include <tuple>
-#if defined(CATCH_CONFIG_WINDOWS_SEH)
-#include <windows.h>
```
Comment (horenmar) [inline tests/SelfTest/UsageTests/Misc.tests.cpp]: Use `<catch2/internal/catch_windows_h_proxy.hpp>`, it defines the `NO_MINMAX`, `LEAN_AND_MEAN` macros etc.

File: tests/SelfTest/UsageTests/Misc.tests.cpp [hunk 3]
```diff
@@ -515,22 +512,3 @@ TEMPLATE_TEST_CASE_SIG("#1954 - 7 arg template test case sig compiles", "[regres
...
-        RaiseException(0xC0000005, 0, 0, NULL);
-    }
-    __except (1)
-    {
-
-    }
-}
-
-
-TEST_CASE("Validate SEH behavior", "[FatalConditionHandler][CATCH_CONFIG_WINDOWS_SEH]")
```
Comment (horenmar) [inline tests/SelfTest/UsageTests/Misc.tests.cpp]: You will want to add `[approvals]` tag in there.

**Comment by horenmar** [comment]
Can you also add a test that unhandled exception still fails tests? To hide the test from standard run, add `[.approvals]` tag to it. (`[approvals]` is a special tag for tests that shouldn't be run as part of approval tests, `.` prefix is a short for `[.]` which hides the test unless it is explicitly selected).


Otherwise LGTM.

**Comment by horenmar** [comment]
I rebased the PR to contain the changes to JIT debugging, but the issue is still there: exception escaping the binary into CTest still causes wait until timeout.

**Comment by Alan-Jowett** [comment]
Let me take a look and see what is happening.

**Comment by Alan-Jowett** [comment]
Will take a look at this when I get back next year. Have a great new year.

**Comment by horenmar** [comment]
@Alan-Jowett Thanks for the PR, I am going to drop the failing test and merge the other parts.

It would be appreciated if you still tried to solve the issue with the JIT debugger on AppVeyor, but even without that this is still an improvement over what is there right now.

**Comment by alvinhochun** [comment]
Is it possible to backport this change to v2.x? I have hit the same issue with ASAN using LLVM/Clang.

**Comment by horenmar** [comment]
I am willing to merge a PR that does the backport (inc. tests)

**Comment by ScottHutchinson** [comment]
> Is it possible to backport this change to v2.x?

My team will try to do this, unless @alvinhochun or somebody else is already working on it.

**Comment by alvinhochun** [comment]
Thanks, I haven't started backporting this for real, so you can do it if you would like to.

**Comment by ScottHutchinson** [comment]
I have manually tested the fix locally and it works. I expect to submit a PR by Monday.
