### PR TITLE
Specify __cdecl on main/wmain, as required by x86 (fixes #2486).

### LINKED ISSUE #2486: CATCH_CONFIG_MAIN isn't __cdecl, causing x86 build failures
**Describe the bug**
See title

**Expected behavior**
#define CATCH_CONFIG_MAIN works on x86.

**Reproduction steps**
Building on x86:
```c++
#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>

TEST_CASE("passes")
{
    constexpr int x{ 1 };
    constexpr int y{ 1 };
    REQUIRE(x == 1);
}

Current workaround:
```c++
#define CATCH_CONFIG_RUNNER
#include <catch2/catch.hpp>

// Using #define CATCH_CONFIG_MAIN would be nicer, but it fails to specify __cdecl, causing a build failure on x86.
extern "C" int __cdecl wmain(int argc, wchar_t* argv[])
{
    return Catch::Session{}.run(argc, argv);
}

TEST_CASE("passes")
{
    constexpr int x{ 1 };
    constexpr int y{ 1 };
    REQUIRE(x == 1);
}
```

**Platform information:**
 - OS: **Windows NT**
 - Compiler+version: **MSVC v19.30.30795.3**
 - Catch version: **v2.13.8**

### PR DESCRIPTION
**Pull request by davidmatson**

### CODE REVIEW

File: include/internal/catch_default_main.hpp [hunk 1]
```diff
@@ -15,7 +15,7 @@
 
 #if defined(CATCH_CONFIG_WCHAR) && defined(CATCH_PLATFORM_WINDOWS) && defined(_UNICODE) && !defined(DO_NOT_USE_WMAIN)
 // Standard C/C++ Win32 Unicode wmain entry point
-extern "C" int wmain (int argc, wchar_t * argv[], wchar_t * []) {
+extern "C" int __cdecl wmain (int argc, wchar_t * argv[], wchar_t * []) {
```
Comment (davidmatson) [inline include/internal/catch_default_main.hpp]: Are there compilers that support wmain but don't have __cdecl? If so, we'd need to chain to another define, such as:

```c++
#ifndef CDECL
#ifdef MSVC
#define CDECL __cdecl
#else
#define CDECL
#endif
#endif
```

Comment (horenmar) [reply include/internal/catch_default_main.hpp]: I don't think there are any.

File: single_include/catch2/catch.hpp [hunk 2]
```diff
@@ -17531,7 +17531,7 @@ namespace Catch {
 extern "C" int wmain (int argc, wchar_t * argv[], wchar_t * []) {
 #else
 // Standard C/C++ main entry point
-int main (int argc, char * argv[]) {
+int __cdecl main (int argc, char * argv[]) {
```
Comment (horenmar) [inline single_include/catch2/catch.hpp]: No changes to `single_include` as part of PRs!
```suggestion
int main (int argc, char * argv[]) {
```

**Comment by horenmar** [comment]
I was gonna say that I am surprised this passes CI, but v2 used to use travis for non-Windows CI and that is dead.

Sprinkling `__cdecl` around will not compile with non-MSVC compilers, so it will need to be conditional. Alternatively, the warning that causes the compilation failure with /WX can be supressed.

**Comment by davidmatson** [comment]
> Sprinkling `__cdecl` around will not compile with non-MSVC compilers, so it will need to be conditional.

Done - thanks for taking a look!

File: include/internal/catch_default_main.hpp [hunk 3]
```diff
@@ -13,12 +13,20 @@
 
 #ifndef __OBJC__
 
+#ifndef CDECL
```
Comment (horenmar) [inline include/internal/catch_default_main.hpp]: I don't like unnamespaced macros, so I would prefer this to be

```suggestion
#ifndef CATCH_INTERNAL_CDECL
```

Comment (davidmatson) [reply include/internal/catch_default_main.hpp]: Sure; done.

File: include/internal/catch_default_main.hpp [hunk 4]
```diff
@@ -13,12 +13,20 @@
 
 #ifndef __OBJC__
 
+#ifndef CATCH_INTERNAL_CDECL
+#ifdef _MSC_VER
```
Comment (dimztimz) [inline include/internal/catch_default_main.hpp:17]: IMO it would be a good idea to additionally constrain this even more to just 32bit x86 with the [predefined macro _M_IX86](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170).

> `_M_IX86` Defined as the integer literal value 600 for compilations that target x86 processors. This macro isn't defined for x64 or ARM compilation targets.

Comment (davidmatson) [reply include/internal/catch_default_main.hpp:17]: I believe the convention, when specifying __cdecl, is always to specify it though rather than making it arch-specific. (I believe the requirement is for all architectures, it's just technically no different on some so it doesn't cause a problem in practice if it's not there.)

For example:
"On ARM and x64 processors, __cdecl is accepted but typically ignored by the compiler."
https://docs.microsoft.com/en-us/cpp/cpp/cdecl?view=msvc-170
