### PR TITLE
Suppress clang-tidy modernize-avoid-c-arrays for TEMPLATE_TEST_CASE

### LINKED ISSUE #2095: TEMPLATE_TEST_CASE breaks clang-tidy check modernize-avoid-c-arrays
**Describe the bug**
`TEMPLATE_TEST_CASE` uses a C array in its definition, which breaks the clang-tidy check `modernize-avoid-c-arrays`.

**Expected behavior**
clang-tidy shouldn't report anything.

**Reproduction steps**

```cpp
TEMPLATE_TEST_CASE("", "", int) {} // this should be enough
```

**Platform information:**

 - OS: WSL2 Ubuntu 20.04
 - Compiler+version: GCC 10.2, clang-tidy 12
 - Catch version: Head

### PR DESCRIPTION
**Pull request by rutayan**
## Description

- Suppress the clang-tidy warnings `cppcoreguidelines-avoid-c-arrays`, `modernize-avoid-c-arrays` for:
https://github.com/catchorg/Catch2/blob/0de60d8e7ead1ddd5ba8c46b901c122eac20bf94/src/catch2/internal/catch_template_test_registry.hpp#L87

- Suppress the clang-tidy warnings `cppcoreguidelines-avoid-c-arrays`, `modernize-avoid-c-arrays` for:
https://github.com/catchorg/Catch2/blob/0de60d8e7ead1ddd5ba8c46b901c122eac20bf94/src/catch2/internal/catch_template_test_registry.hpp#L88

- Suppress `cppcoreguidelines-avoid-non-const-global-variables` for: 
https://github.com/catchorg/Catch2/blob/0de60d8e7ead1ddd5ba8c46b901c122eac20bf94/src/catch2/internal/catch_template_test_registry.hpp#L92

### The why:
I am using catch2 `TEMPLATE_TEST_CASE` for my project. My project is seeing clang-tidy failures as seen by someone else also #2095.

## GitHub Issues

Closes #2095

### CODE REVIEW

File: src/catch2/internal/catch_template_test_registry.hpp [hunk 1]
```diff
@@ -84,11 +84,12 @@
             struct TestName{\
                 TestName(){\
                     size_t index = 0;                                    \
-                    constexpr char const* tmpl_types[] = {CATCH_REC_LIST(INTERNAL_CATCH_STRINGIZE_WITHOUT_PARENS, __VA_ARGS__)};\
-                    using expander = size_t[];\
+                    constexpr char const* tmpl_types[] = {CATCH_REC_LIST(INTERNAL_CATCH_STRINGIZE_WITHOUT_PARENS, __VA_ARGS__)}; /* NOLINT(cppcoreguidelines-avoid-c-arrays,modernize-avoid-c-arrays) */\
```
Comment (horenmar) [inline src/catch2/internal/catch_template_test_registry.hpp]: This warning has at least one more alias: `hicpp-avoid-c-arrays`
```suggestion
                    constexpr char const* tmpl_types[] = {CATCH_REC_LIST(INTERNAL_CATCH_STRINGIZE_WITHOUT_PARENS, __VA_ARGS__)}; /* NOLINT(cppcoreguidelines-avoid-c-arrays,modernize-avoid-c-arrays,hicpp-avoid-c-arrays) */\
```

([clang-tidy's handling of aliases is pretty damn bad](https://github.com/llvm/llvm-project/issues/54319))

File: src/catch2/internal/catch_template_test_registry.hpp [hunk 2]
```diff
@@ -84,11 +84,12 @@
...
+                    using expander = size_t[]; /* NOLINT(cppcoreguidelines-avoid-c-arrays,modernize-avoid-c-arrays) */\
                     (void)expander{(reg_test(Types{}, Catch::NameAndTags{ Name " - " + std::string(tmpl_types[index]), Tags } ), index++)... };/* NOLINT */ \
                 }\
             };\
+            /* NOLINTNEXTLINE(cppcoreguidelines-avoid-non-const-global-variables) */\
             static int INTERNAL_CATCH_UNIQUE_NAME( globalRegistrar ) = [](){\
```
Comment (horenmar) [inline src/catch2/internal/catch_template_test_registry.hpp]: Actually, is there a reason not to make this `const`?

Comment (rutayan) [reply src/catch2/internal/catch_template_test_registry.hpp]: I am still pretty new to the code. I did try with `const` and all the test seem to pass. I am assuming it might be ok to just make it `const`.

File: src/catch2/internal/catch_template_test_registry.hpp (hunk 1 above)
Comment (rutayan) [reply src/catch2/internal/catch_template_test_registry.hpp]: Thanks for the catch. I have added the alias now. I reviewed the clang-tidy page and it seems adding `hicpp-avoid-c-arrays` should cover all the aliases: https://clang.llvm.org/extra/clang-tidy/checks/modernize/avoid-c-arrays.html

File: src/catch2/internal/catch_template_test_registry.hpp (hunk 2 above)
Comment (rutayan) [reply src/catch2/internal/catch_template_test_registry.hpp]: Done: 5dab39f6

File: src/catch2/internal/catch_template_test_registry.hpp (hunk 1 above)
Comment (rutayan) [reply src/catch2/internal/catch_template_test_registry.hpp]: Added the requested alias: b6e4e839

File: src/catch2/internal/catch_template_test_registry.hpp (hunk 2 above)
Comment (horenmar) [reply src/catch2/internal/catch_template_test_registry.hpp]: If the tests compile & pass, it should be fine. This isn't a place that tests can't reach, so you can rely on them.

**Comment by horenmar** [comment]
Thanks

**Comment by rutayan** [comment]
Thanks for the review! My first open source check-in. I will have a boba-tea for celebration.
