### PR TITLE
Use console reporter's totals summary for compact reporter

### LINKED ISSUE #878: Compact reporter does not handle [!shouldfail] properly
## Description
Compact reporter does not handle the `[!shouldfail]` tag properly. Given this code (from #876):
```cpp
bool thisThrows() {
    throw std::runtime_error("Boom");
}

TEST_CASE("#748 - captures with unexpected exceptions", "[!shouldfail]") {
    int answer = 42;
    CAPTURE(answer);
    // the message should be printed on the first two sections but not on the third
    SECTION("outside assertions") {
        thisThrows();
    }
    SECTION("inside REQUIRE_NOTHROW") {
        REQUIRE_NOTHROW(thisThrows());
    }
    SECTION("inside REQUIRE_THROWS") {
        REQUIRE_THROWS(thisThrows());
    }
}
```
compact reporter's output is
```
<snip>
Passed all 0 test cases with 1 assertion.
```
which, while kind-of correct, is surprising. Standard console reporter's output looks like this:
```
<snip>
test cases: 1 | 1 failed as expected
assertions: 3 | 1 passed | 2 failed as expected
```
which is much clearer about what happened and should be in some way replicated by the compact reporter.

### Extra information
* Catch version: **v1.8.2**

### PR DESCRIPTION
**Pull request by psalz**
This changes the compact reporter's summary of test run totals to use the same format as the console reporter. This means that while output is no longer on a single line (two instead), it now includes totals for `failedButOk` test cases and assertions, which were previously missing.

Fixes #878.

### CODE REVIEW

File: src/catch2/reporters/catch_reporter_helpers.cpp [hunk 1]
```diff
@@ -235,4 +235,88 @@ namespace Catch {
...
+            Colour::Code colour;
+            std::vector<std::string> rows;
+        };
+
+        static void printSummaryRow( StringRef label,
+                                     std::vector<SummaryColumn> const& cols,
+                                     std::size_t row,
+                                     std::ostream& stream,
+                                     ColourImpl& colour ) {
+            for ( auto col : cols ) {
```
Comment (horenmar) [inline src/catch2/reporters/catch_reporter_helpers.cpp]: Does this need to be a copy? From a quick glance I would say no, the code does not modify the `SummaryColumn` here.

(I know it is like this in the original code, but I am looking through it again here and hoo boy, it is a mess)

File: src/catch2/reporters/catch_reporter_helpers.cpp [hunk 2]
```diff
@@ -235,4 +235,88 @@ namespace Catch {
         out << "\n\n" << std::flush;
     }
 
+    namespace {
+        struct SummaryColumn {
+            SummaryColumn( std::string _label, Colour::Code _colour ):
+                label( CATCH_MOVE( _label ) ), colour( _colour ) {}
+            SummaryColumn addRow( std::uint64_t count ) {
```
Comment (horenmar) [inline src/catch2/reporters/catch_reporter_helpers.cpp]: This is another big mess. I don't feel like saddling you with fixing the implementation, but from looking at it, the signature does not make sense either.

It returns a copy, but not before modifying the current state of the instance, so something like

`SummaryColumn&& addRow(std::uint64_t count) &&`

makes more sense IMO, so we do not copy all the rows every time (which makes repeated calls to `addRow` have quadratic complexity), and the `&&` qualifier means that this won't be modifying any lvalues.

**Comment by horenmar** [comment]
Looks good, with two drive-by fixes since you are already touching that code. Honestly you can ignore them if you want 🤷

**Comment by psalz** [comment]
Sure, no problem. I did a refactoring pass as a fixup commit, will squash once approved.

---

Speaking of messes, I originally planned to do a larger refactoring of how `[!shouldfail]` and `[!mayfail]` are being handled, as there are a few things that have bothered me for a while (e.g. the way a *passing* `[!shouldfail]` test case is "reported"), but I gave up after a couple of hours because I found the whole logic to be very confusing. For example that a failed assertion in a `[!shouldfail]` is not `isOk` because it doesn't have `ResultDisposition::SuppressFail` (which only seems to be used for `CHECKED_IF/ELSE`), or [whatever is happening here](https://github.com/catchorg/Catch2/blob/8ce92d2c7288b6b3261caf1c016f8a779b6a8efc/src/catch2/internal/catch_run_context.cpp#L250-L253). If I ever find some time I would like to revisit this again, though.

File: src/catch2/reporters/catch_reporter_helpers.cpp [hunk 3]
```diff
@@ -236,36 +236,50 @@ namespace Catch {
...
-                    while ( oldRow.size() > row.size() )
-                        row = ' ' + row;
+        class SummaryColumn {
+        public:
+            SummaryColumn( std::string suffix, Colour::Code colour ):
+                m_suffix( CATCH_MOVE( suffix ) ), m_colour( colour ) {}
+
+            SummaryColumn&& addRow( std::uint64_t count ) && {
+                std::string row = std::to_string(count);
+                auto const new_width = std::max( m_width, row.size() );
```
Comment (horenmar) [inline src/catch2/reporters/catch_reporter_helpers.cpp:246]: you want `m_width` to be `size_t` as well.

Comment (psalz) [reply src/catch2/reporters/catch_reporter_helpers.cpp:246]: Right, fixed.

File: src/catch2/reporters/catch_reporter_helpers.cpp [hunk 4]
```diff
@@ -236,36 +236,50 @@ namespace Catch {
...
+                if ( new_width > m_width ) {
+                    for ( auto& oldRow : m_rows ) {
+                        oldRow = std::string( new_width - m_width, ' ' )
+                                     .append( oldRow );
```
Comment (horenmar) [inline src/catch2/reporters/catch_reporter_helpers.cpp]: Tiny nitpick:
```
oldRow.insert(0, new_width - m_width, ' ');
```

is never worse and in _some_ (rather specific) circumstances actually better.

Comment (horenmar) [reply src/catch2/reporters/catch_reporter_helpers.cpp]: Similar change applies to the other branch as well.

**Review by horenmar — APPROVED** [review]
lgtm

**Comment by horenmar** [comment]
Yeah, shouldfail/mayfail is also a "fun" mess. It is what happens when the code is evolved over time for 10+ years 😃

File: src/catch2/reporters/catch_reporter_helpers.cpp (hunk 4 above)
Comment (psalz) [reply src/catch2/reporters/catch_reporter_helpers.cpp]: Fixed and squashed
